version: '3.8'
name: amtsblatt-gpt
services:
  app:
    build: .
    env_file: [".env"]
    restart: "unless-stopped"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      CHECK_EMAIL_INTERVAL: ${CHECK_EMAIL_INTERVAL}
